/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* src = "mux_estruc.v:3" *)
module mux_estruc(out, c, a, b);
  (* src = "mux_estruc.v:9" *)
  wire _0_;
  (* src = "mux_estruc.v:6" *)
  input a;
  (* src = "mux_estruc.v:6" *)
  input b;
  (* src = "mux_estruc.v:6" *)
  input c;
  (* src = "mux_estruc.v:7" *)
  wire n0;
  (* src = "mux_estruc.v:7" *)
  wire n1;
  (* src = "mux_estruc.v:5" *)
  output out;
  assign _0_ = ~(* src = "mux_estruc.v:9" *) c;
  assign n0 = b &(* src = "mux_estruc.v:9" *)  _0_;
  assign n1 = a &(* src = "mux_estruc.v:10" *)  c;
  assign out = n1 |(* src = "mux_estruc.v:11" *)  n0;
endmodule
